### ISSUE TITLE
dotnet test fails when decimal separator is not dot in regional format

### ISSUE THREAD

**Issue by codepic** [microsoft/PSRule#1405]
**Description of the issue**

When current culture decimal separator is not `.`, the `dotnet test` fails

**To Reproduce**

Set the regional format as follows:
![image](https://user-images.githubusercontent.com/3933589/210177295-e64e38b4-1a39-4a6b-ba28-2f3dd0eed697.png)

```powershell
cd PSRule
dotnet test
```

**Expected behaviour**

Tests should pass

**Error output**

```text
[xUnit.net 00:00:02.66]     PSRule.AssertTests.LessOrEqual [FAIL]
  Failed PSRule.AssertTests.LessOrEqual [7 ms]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at PSRule.AssertTests.LessOrEqual() in C:\Users\JaniHyytiäinen\src\OpsOps.PSRule\tests\PSRule.Tests\AssertTests.cs:line 1023
[xUnit.net 00:00:02.81]     PSRule.AssertTests.GreaterOrEqual [FAIL]
[xUnit.net 00:00:02.83]     PSRule.AssertTests.Less [FAIL]
  Failed PSRule.AssertTests.GreaterOrEqual [3 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at PSRule.AssertTests.GreaterOrEqual() in C:\Users\JaniHyytiäinen\src\OpsOps.PSRule\tests\PSRule.Tests\AssertTests.cs:line 887
  Failed PSRule.AssertTests.Less [14 ms]
  Error Message:
   Assert.False() Failure
Expected: False
Actual:   True
  Stack Trace:
     at PSRule.AssertTests.Less() in C:\Users\JaniHyytiäinen\src\OpsOps.PSRule\tests\PSRule.Tests\AssertTests.cs:line 955
[xUnit.net 00:00:02.87]     PSRule.AssertTests.Greater [FAIL]
  Failed PSRule.AssertTests.Greater [3 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at PSRule.AssertTests.Greater() in C:\Users\JaniHyytiäinen\src\OpsOps.PSRule\tests\PSRule.Tests\AssertTests.cs:line 819

Failed!  - Failed:     4, Passed:   274, Skipped:     0, Total:   278, Duration: 5 s - PSRule.Tests.dll (net6.0)
```

**Module in use and version:**

- Module: PSRule
- Version: **branch: main**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

All of the failing tests initialize the value as decimal with a dot separator:

```cs
value = GetObject((name: "value", value: "4.5"));
Assert.True(assert.Greater(value, "value", 2, convert: true).Result);
```
When regional format is set to `en-US`, the tests pass:

![image](https://user-images.githubusercontent.com/3933589/210177486-3afc1dc0-9060-4485-8881-bb9f5ea2d0a0.png)

```text
cd PSRule
dotnet test
...
Passed!  - Failed:     0, Passed:   278, Skipped:     0, Total:   278, Duration: 5 s - PSRule.Tests.dll (net6.0)
```

**Comment by BernieWhite** [comment]
@codepic Thanks for reporting the issue.

Instead of `.` how would this normally be represented with your recommended culture settings?
